name: Publish

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack
        run: dotnet pack ./KafkaFlow.sln --include-symbols --include-source -c Release /p:Version=${{ github.event.release.tag_name }} -o ./drop

      - name: Authenticate against Repository
        run: dotnet nuget add source --username Skyppid --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GitHub "https://nuget.pkg.github.com/CarbonFreed-AI/index.json"

      - name: Publish
        run: dotnet nuget push ./drop/**/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "GitHub" --skip-duplicate

      - name: Print Version
        run: echo ${{ github.event.release.tag_name }}
